/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./node_modules/flowbite-react/lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        'twOfficial': '#FF5FA2',
        'nayeonMain': '#49c0ec',
        'jeongyeonMain': '#a3cc54',
        'momoMain': '#e67ea3',
        'sanaMain': '#8c79b4',
        'jihyoMain': '#f9cc85',
        'minaMain': '#71c7d4',
        'dahyunMain': '#fefefe',
        'chaeyoungMain':'#e62722',
        'tzuyuMain' : '#2253a3'
      }
    },
  },
  safelist: [
    'bg-twOfficial',
    'text-twOfficial',
    'border-twOfficial',
    'border-nayeonMain',
    'border-jeongyeonMain',
    'border-momoMain',
    'border-sanaMain',
    'border-jihyoMain',
    'border-minaMain',
    'border-dahyunMain',
    'border-chaeyoungMain',
    'border-tzuyuMain',
    'text-nayeonMain',
    'text-jeongyeonMain',
    'text-momoMain',
    'text-sanaMain',
    'text-jihyoMain',
    'text-minaMain',
    'text-dahyunMain',
    'text-chaeyoungMain',
    'text-tzuyuMain',
    'bg-nayeonMain',
    'bg-jeongyeonMain',
    'bg-momoMain',
    'bg-sanaMain',
    'bg-jihyoMain',
    'bg-minaMain',
    'bg-dahyunMain',
    'bg-chaeyoungMain',
    'bg-tzuyuMain',
    'hover:bg-twOfficial',
    'hover:text-twOfficial',
    'hover:border-twOfficial',
    'hover:bg-nayeonMain',
    'hover:text-nayeonMain',
    'hover:border-nayeonMain',
    'hover:bg-jeongyeonMain',
    'hover:text-jeongyeonMain',
    'hover:border-jeongyeonMain',
    'hover:bg-momoMain',
    'hover:text-momoMain',
    'hover:border-momoMain',
    'hover:bg-sanaMain',
    'hover:text-sanaMain',
    'hover:border-sanaMain',
    'hover:bg-jihyoMain',
    'hover:text-jihyoMain',
    'hover:border-jihyoMain',
    'hover:bg-minaMain',
    'hover:text-minaMain',
    'hover:border-minaMain',
    'hover:bg-dahyunMain',
    'hover:text-dahyunMain',
    'hover:border-dahyunMain',
    'hover:bg-chaeyoungMain',
    'hover:text-chaeyoungMain',
    'hover:border-chaeyoungMain',
    'hover:bg-tzuyuMain',
    'hover:text-tzuyuMain',
    'hover:border-tzuyuMain',

    
  ],
  plugins: [
    require("flowbite/plugin")
  ],
};
