
import AccsGrid from "@/components/AccsGrid";
import HomeBotoesGrid from "@/components/HomeBotoesGrid";
import BotoesBtn from "@/components/BotoesBtn";
import Sidebar from "@/components/Sidebar";
import Image from "next/image";
import CelDialer from "@/components/CelDialer";

const isNome = "sim";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  
  
  return (
    <main className="flex">
      
      
      <aside id="default-sidebar" className="hidden sm:ml-0 sm:block sm:z-20  " aria-label="Sidebar">
            <Sidebar  isNomes={isNome} />
      </aside>
      
      <div className="w-full max-h-screen-lg mx-auto md:p-4 ">
      <AccsGrid />
      </div>
      
    </main>
  );
}



{/* <div className="md:p-4 md:pt-8"><HomeBotoesGrid /></div>
      <div className="md:p-4 md:pt-0"><HomeBotoesGrid isNomes={isNome} /></div>  */}